@base_url=http://localhost:3000
@basic_auth_luffy=Basic bHVmZnk6bmlrdQ==
@basic_auth_naruto=Basic bmFydXRvOnJhbWVu
@basic_auth_hit=Basic dXNlcjExNTpyYW1lbg==

@basic_auth_kakashi=Basic a2FrYXNoaTpyYW1lbg== 
@kakashi_jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia2FrYXNoaSIsImlhdCI6MTczMDg4NjIwOH0.6kxcWO7cZtrAGHCQhUDRMtJJHPp6vLy40GcvBbi6GyI
{{base_url}}/
###
{{base_url}}/drive/simu
Authorization: {{basic_auth_luffy}}
###
{{base_url}}/drive
Authorization: {{ basic_auth_luffy }}
###
{{base_url}}/drive
Authorization: {{ basic_auth_naruto }}
###
{{base_url}}/drive/souvenirs/2024
Authorization: {{ basic_auth_luffy }}
###
{{base_url}}/drive/travail
Authorization: {{ basic_auth_luffy }}
###
{{base_url}}/drive/info/anime.txt
Authorization: {{ basic_auth_hit }}
###
{{base_url}}/drive/info/souvenirs/souvenir1.txt
Authorization: {{ basic_auth_luffy }}
###
{{base_url}}/drive/content/souvenirs/souvenir1.txt
Authorization: {{ basic_auth_luffy }}
###
{{base_url}}/drive/move/souvenirs/2024/souvenir1.txt/to/hello.txt
Authorization: {{ basic_auth_luffy }}
###
POST {{base_url}}/drive/content/souvenir2.txt
Content-Type: text/plain
Authorization: Bearer {{kakashi_jwt}}

Hello.
Ceci est un fichier texte.

Paragraphe 2
###
{{base_url}}/drive
Authorization: Bearer {{kakashi_jwt}}