@base_url=http://localhost:3000
POST {{base_url}}/users/register
Content-Type: application/json

{
  "login":"naruto",
  "password":"ramen"
}
###
POST {{base_url}}/users/register
Content-Type: application/json

{
  "login":"user{{$randomInt 1 1000}}",
  "password":"ramen"
}
###
POST {{base_url}}/users/register
Content-Type: application/json

{
  "login":"kakashi",
  "password":"ramen"
}
###
POST {{base_url}}/users/login
Content-Type: application/json

{
  "login":"kakashi",
  "password":"ramen"
}
