@base_url=http://localhost:3000
###
POST {{base_url}}/users/register
Content-Type: application/json

{
  "email":"drvet@vet.com",
  "password": "pwd",
  "isVet": true
}
###
# @name login
POST {{base_url}}/users/login
Content-Type: application/json

{
  "email":"drvet@vet.com",
  "password": "pwd"
}
###
POST {{base_url}}/users/register
Content-Type: application/json

{
  "email":"mail@mail.com",
  "password": "pwd"
}
###
POST {{base_url}}/users/login
Content-Type: application/json

{
  "email":"mail@mail.com",
  "password": "pwd"
}
###
@authToken={{login.response.body.token}}
###
GET {{base_url}}/animals
Authorization: Bearer {{authToken}}
###
POST {{base_url}}/animals
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "name": "Milou {{$randomInt 1 200}}"
}
###
PUT {{base_url}}/animals/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "name": "Idéfix {{$randomInt 1 200}}"
}
###
DELETE {{base_url}}/animals/1
Authorization: Bearer {{authToken}}
###
DELETE {{base_url}}/animals/2
Authorization: Bearer {{authToken}}
###
POST {{base_url}}/appointments
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "idVet" : 1,
  "idAnimal": 1,
  "date": "2024-07-01T09:30:00.0Z"
}
###
POST {{base_url}}/appointments
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "idVet" : 1,
  "idAnimal": 2,
  "date": "2024-07-02T10:00:00.0Z"
}
###
GET {{base_url}}/appointments
Authorization: Bearer {{authToken}}