
http://{{host}}/api/cards
###
POST http://{{host}}/api/cards
Content-Type: application/json

{
  "name": "test card",
  "attack": 50,
  "type": "monster"
}
###
# @name login
POST http://{{host}}/api/users/login
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "1234"
}
###
POST http://{{host}}/api/users/register
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "1234"
}
###
@authToken = {{login.response.body.token}}
###
GET http://{{host}}/api/folders?path=/
Authorization: Bearer {{authToken}}
###
GET http://{{host}}/api/folders?path=/photos
Authorization: Bearer {{token}}
###
POST http://{{host}}/api/folders
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "path":"/photos"
}
###
POST http://{{host}}/api/folders
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "path":"/photos/2024"
}
###
POST http://{{host}}/api/folders
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "path":"/photos/2025"
}
###
POST http://localhost:3000/api/folders
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "path":"/documents"
}
###
POST http://localhost:3000/api/folders
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "path":"/documents/"
}

