
http://{{host}}/api/cards
###
POST http://{{host}}/api/cards
Content-Type: application/json

{
  "name": "test card",
  "attack": 50,
  "type": "monster"
}
###
POST http://{{host}}/api/users/register
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "1234"
}
###
POST http://{{host}}/api/users/login
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "1234"
}
###
GET http://{{host}}/api/folders?path=/
Authorization: Bearer {{token}}
###
GET http://{{host}}/api/folders?path=/photos
Authorization: Bearer {{token}}
###
POST http://{{host}}/api/folders/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "path":"/photos"
}
###
POST http://localhost:3000/api/folders/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "path":"/documents"
}

